package com;

public enum ConfigPropertyKeys {
	NUMBER_OF_CHROMOSOMES_PER_GENERATION,
	NUMBER_OF_GENERATIONS_TO_RUN,
	DUPLICATE_LOCATION_SCORE_PENALTY,
	CHROMOSOME_LENGTH_MULTIPLIER,
	CHROMOSOME_SHUFFLE_ODDS_MULTIPLIER,
	SUPER_INDIVIDUAL_BONUS_FIRST,
	SUPER_INDIVIDUAL_BONUS_SECOND,
	SUPER_INDIVIDUAL_BONUS_THIRD,
	FIRST_MUTATION_PERCENTAGE,
	SECOND_MUTATION_PERCENTAGE,
	THIRD_MUTATION_PERCENTAGE
}
